kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: ken
  namespace: dev
roleRef:
  kind: Role
  name: view-role
  apiGroup: rbac.authorization.k8s.io