kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-binding
  namespace: prometheus
subjects:
- kind: ServiceAccount
  name: carol
  apiGroup: ""
roleRef:
  kind: Role
  name: test-role
  apiGroup: ""